name: Fortify-CI-Flow

on:
  push:
    branches:
      - newmaster
  pull_request:
    types: [opened, synchronize, reopened]    

jobs:
  Build-FortifyScan:

    runs-on: [self-hosted, linux, X64, philips]
    container:
      image: maven:3.8.4-jdk-8
      
    steps:
    - name: Check-out source code
      uses: actions/checkout@v3    

    - name: Java-Build
      run: mvn -B clean verify
  
    - name: Fortify Scan (Java)
      uses: philips-internal/fortify-linux-action@main
      env:
          FORTIFY_TOKEN: ${{ secrets.FORTIFY_TOKEN }}
          FORTIFY_HOST_URL: ${{ secrets.FORTIFY_URL }}
          FORTIFY_PROJECT_NAME: saas-factory
          FORTIFY_VERSION_NAME: fortify-sridhar
      with:
          language: Java
          javaVersion: 8
          exclude: "./**/test/*.java"
